title: Ubiqui-fi Docs
description: Developer documentation for Ubiqui-fi products.
theme: just-the-docs

url: https://ubiqui-fi.github.io/docs/

aux_links:
  Ubiqui-fi on Github: https://github.com/ubiqui-fi

last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y at %I:%M %p"

gh_edit_link: true
gh_edit_repository: https://ubiqui-fi.github.io/docs/
gh_edit_branch: main
gh_edit_view_mode: tree

back_to_top: true
back_to_top_text: Back to top

collections:
  newtab:
    output: true
  website:
    output: true

just_the_docs:
  collections:
    newtab:
      name: New Tab
    website:
      name: Website

callouts:
  info:
    title: Info
    color: blue